name: Trigger Vercel Deploy

on:
  push:
    branches:
      - main # Change this if your default branch is 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Vercel Deploy Hook
        run: curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}
